name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    #Operating systems
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022]

    steps:
      - uses: actions/checkout@v3

      #Cmake (in Debug mode)
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build_debug -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build ${{github.workspace}}/build_debug --config Debug

      - name: Run Tests
        working-directory: ${{github.workspace}}/build_debug
        run: ctest -C Debug --output-on-failure